install:
  - choco install gitlink -y
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-desktop.ps1'))

assembly_info:
  patch: false

configuration:
  - Release

platform:
  - Any CPU

before_build:
  - nuget restore

build_script:
  - cmd: msbuild UIAComWrapper.sln "/p:Configuration=%CONFIGURATION%;Platform=%PLATFORM%"

  - cmd: GitLink . -u https://github.com/TestStack/UIAComWrapper -c %CONFIGURATION%

cache:
  - packages -> **\packages.config